-- Migration: Create readings table with RLS policies
-- Stage 1: Tea Warehouse Monitoring System
-- Created: 2025-12-13

-- Create readings table
CREATE TABLE IF NOT EXISTS public.readings (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  device_id text NOT NULL,
  temperature float4 NOT NULL,
  humidity float4 NOT NULL
);

-- Add comment to table
COMMENT ON TABLE public.readings IS 'Temperature and humidity readings from ESP32 devices';

-- Add comments to columns
COMMENT ON COLUMN public.readings.id IS 'Unique identifier for each reading';
COMMENT ON COLUMN public.readings.created_at IS 'Timestamp when the reading was uploaded';
COMMENT ON COLUMN public.readings.device_id IS 'Device/warehouse identifier (e.g., tea_room_01)';
COMMENT ON COLUMN public.readings.temperature IS 'Temperature in Celsius (°C)';
COMMENT ON COLUMN public.readings.humidity IS 'Relative humidity (%)';

-- Enable Row Level Security
ALTER TABLE public.readings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "allow anon insert" ON public.readings;
DROP POLICY IF EXISTS "allow authenticated select" ON public.readings;

-- Policy 1: Allow anonymous users to INSERT data (for ESP32 devices)
CREATE POLICY "allow anon insert"
  ON public.readings
  FOR INSERT
  TO anon
  WITH CHECK (
    length(device_id) > 0 AND length(device_id) < 128 AND
    temperature > -50 AND temperature < 100 AND
    humidity >= 0 AND humidity <= 100
  );

-- Policy 2: Allow authenticated users to SELECT data (for iOS app)
CREATE POLICY "allow authenticated select"
  ON public.readings
  FOR SELECT
  TO authenticated
  USING (true);

-- Create index on created_at for faster time-based queries
CREATE INDEX IF NOT EXISTS idx_readings_created_at ON public.readings(created_at DESC);

-- Create index on device_id for filtering by device
CREATE INDEX IF NOT EXISTS idx_readings_device_id ON public.readings(device_id);

